### ISSUE TITLE
Crash on following tracker format

### ISSUE THREAD

**Issue by g8dhe** [philcrump/habrotate#11]
Maybe something to do with time before sentence ID in the tracker format ???

C:\Program Files (x86)\HABRotate>habrotate-cli
##### HABrotate

Parsing config.json..
Receiver Station Location: Lat: 50.8125 Lon: -0.3751 Altitude: 20.0
UDP Configuration: IP: 127.0.0.1 Port: 12000
Control Configuration: Hysteresis = 2 degrees, Overshoot = 1 degrees.
Querying flights..
1: PS-13 434.500 THOR8 OLIVIA 8/250 Enable RSID - TODAY
2: CHEAPO14 - TODAY
3: EDUHABDEV - TODAY
4: Gilwell 24 SSDV
5: Gilwell 24 #1
6: XABEN75
Select Flight number: 3
Querying position..
Traceback (most recent call last):
  File "habrotate-cli.py", line 183, in <module>
  File "habrotate-cli.py", line 97, in grab_position
  File "habrotate-cli.py", line 97, in <lambda>
KeyError: 'sentence_id'

C:\Program Files (x86)\HABRotate>

from habitat logtail format was ;

  "payload": "EDUHAB2"

  "latitude": 52.323816, 

  "time": "19:20:34", 

  "_protocol": "UKHAS", 

  "ext_temp": "-5.10", 

  "cutdown": 0, 

  "satellites": "09", 

  "board_temp": "10.00", 

  "longitude": -1.705041, 

  "_sentence": "$$EDUHAB2,19:20:34,181,52.323816,-1.705041,09,1,10.00,-5.10,6565.1,0*2871\n", 

  }, 

```
"configuration_sentence_index": 0

"payload_configuration": "7e0fdceb5d2771a4c3b3bcfe1d4b1371", 

"time_parsed": "2014-07-13T19:20:53Z", 

"flight": "7e0fdceb5d2771a4c3b3bcfe1d4f28c1", 
```

  "_parsed": {

  "altitude": 6565.1, 

  "flightmode": "1", 

  "count": 181,

**Comment by dbrooke** [comment]
Just as a test I globally replaced 'sentence_id' with 'count' and it then worked but of course would no longer work with other payloads.

**Comment by g8dhe** [comment]
Yup that makes sense!

**Comment by philcrump** [comment]
Making anything to rely on habitat, also relies on people filling in the payload docs correctly :/
